const actionTypes = {
  LOAD_WORKOUTS: 'LOAD_WORKOUTS',
  LOAD_WORKOUTS_ERROR: 'LOAD_WORKOUTS_ERROR',
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_SIGNOUT: 'AUTH_SIGNOUT',
  AUTH_SIGNOUT_ERROR: 'AUTH_SIGNOUT_ERROR',
};

export default actionTypes;
