const actionTypes = {
  LOAD_WORKOUTS: 'LOAD_WORKOUTS',
  LOAD_WORKOUTS_ERROR: 'LOAD_WORKOUTS_ERROR',
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
};

export default actionTypes;
