const actionTypes = {
  LOAD_WORKOUTS: 'LOAD_WORKOUTS',
  LOAD_WORKOUTS_ERROR: 'LOAD_WORKOUTS_ERROR',
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  AUTH_SIGNOUT: 'AUTH_SIGNOUT',
  AUTH_SIGNOUT_ERROR: 'AUTH_SIGNOUT_ERROR',
  ADD_USER: 'ADD_USERS',
  ADD_USER_ERROR: 'ADD_USERS_ERROR',
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  SAVE_USER: 'SAVE_USER',

};

export default actionTypes;
